---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    gcp_project: setup-vms-project-1
    gcp_cred_kind: serviceaccount
    gcp_cred_file: /home/filiplez18/credentials/credentialsGCP.json
    zone: europe-west4-a
    region: europe-west4

  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: 'disk-instance'
        size_gb: 10
        source_image: 'projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20190514'
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/cloud-platform
        state: present
      register: disk
    - name: create a network
      gcp_compute_network:
        name: 'network-instance'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/cloud-platform
        state: present
      register: network
    - name: create a address
      gcp_compute_address:
        name: 'address-instance'
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/cloud-platform
        state: present
      register: address
    - name: create a instance
      gcp_compute_instance:
        state: present
        name: dev
        machine_type: f1-micro
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address }}"
                type: 'ONE_TO_ONE_NAT'
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/cloud-platform
      register: instance
...
