- name: "Create GCE instances"
  gce:
    instance_names: "{{ instances_names_list }}"
    zone: "{{ zone }}"
    state: present
    machine_type: "{{ machine_type }}"
    image: "{{ image }}"
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
  register: gce
